services:

  mysql:
    image: mysql:8.0
    container_name: drivefleet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drivefleet
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - drivefleet-net
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app:
    build: .
    container_name: drivefleet-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/drivefleet?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev123
    ports:
      - "8080:8080"
    networks:
      - drivefleet-net

volumes:
  mysql_data:

networks:
  drivefleet-net: